### ISSUE TITLE
Extend test case for fabric to involve multiple organizations in endorsement

### ISSUE THREAD

**Issue by 3100** [hyperledger-labs/yui-relayer#54]
It would be nice to have a test case that can confirm that the mismatch of endorsed commitments is not happening when multiple organizations are involved.
For example, we can extend tm2fab.

**Comment by bluele** [comment]
I think it's helpful to discover the following bug: https://github.com/hyperledger-labs/yui-fabric-ibc/issues/37

**Comment by bluele** [comment]
Currently, there are no test settings for fabric-ibc in this repository.
